# Configuration for the app
name: "PawPrints"
description: "Make Your Mark. Create and sign petitions. Receive official responses."
main_logo: "/images/pawprints-white.svg" # Main logo location in static directory

organization: "Vanderbilt Student Government" # Organization responding to petitions
org_logo: "/images/sg-logo.png" # Logo for the organization


# Determines if you want an additional nav at the top of the app for your organizations resources
# Default set to False
generate_top_nav: False

text:
    header_title: "Make Your Mark" 
    slideshow:
        # Text that shows up in the middle of the slideshow
        bold_text: "Make Your Mark"
        first_line: "Create and sign petitions."
        second_line: "Receive official responses from Student Government."

petitions:
    # Default values that show up when user creates a petition
    default_title: "Action-oriented, one-line statement"
    default_body: "Explanation and reasoning behind your petition. Why should someone sign? How will it improve the community?"

tags:
  - name: "Technology"
  - name: "Academics"
  - name: "Parking & Transportation"
  - name: "Other"
  - name: "Dining"
  - name: "Sustainability"
  - name: "Facilities"
  - name: "Housing"
  - name: "Public Safety"
  - name: "Campus Life"
  - name: "Governance"
  - name: "Clubs & Organizations"
  - name: "Accessibility"
    
email:
  # Email titles
  # Add "Org Name - " to front
  approved: "Your Petition is Published!"
  rejected: "Petition Rejected"
  updated: "A Petition you signed has a status update!"
  responded: "A Petition you signed has a response!"
  reached: "Petition threshold reached"
  needs_approval: "Petition needs approval"
  received: "Petition received"
  reported: "A Petition has been reported by a member of the community."
  charged: "Petition has been charged!"

  header_image: "/images/pawprintsemail.png" # image located in /static/

  colors:
    email_header: "#f49e42" # Color that is at the top of the email header
  
ui:
    colors:
        highlight: "#36454F"
        #hmmmmm
        orange_highlight: "#d8ab4c"
        highlight_hover: "#606d75"
        # highlight_hover: "#e86920"
        dark_text: "#0f0f0f"
        light_text: "#f0f0f0"
        bright_text: "#fff"
        light_background: "#fafafa"
        main_color: "#d8ab4c"
        responded_highlight: "#9d5f4b"
        progress_green: "#18A558"
    slideshow_images:
    # Defines images that show up in the slideshow
    # To add more or less, add another block in the form
    # - url: "location from root of project"
    #   sort_rank: 0
        - url: "/static/images/CampusStock_11.jpg"
          sort_rank: 0
        - url: "/static/images/CampusStock_25.jpg"
          sort_rank: 0
        - url: "/static/images/CampusStock_95.jpg"
          sort_rank: 0
        - url: "/static/images/CampusStock_8.jpg"
          sort_rank: 0
        - url: "/static/images/carousel_1.png"
          sort_rank: 0
        - url: "/static/images/carousel_2.png"
          sort_rank: 0
        - url: "/static/images/carousel_3.png"
          sort_rank: 0

social:
# Data that shows up when sharing to social networks
    title: "VSG"
    image: "/images/pawprintsemail.png" # image located in /static/ (This is usually just the same as the app logo)
    social_links:
      # Links for social media sites, just point it to the root url.
      # - name: "Facebook"
      #   imgURL: "/static/images/facebook_icon.svg"
      #   link: "https://www.facebook.com/sharer.php?u=https://pawprints.rit.edu/"
      - name: "Twitter"
        imgURL: "/static/images/twitter_icon.svg"
        link: "https://twitter.com/intent/tweet?text=&via=&hashtags=&url=https://pawprints.rit.edu/"
      # - name: "Reddit"
      #   imgURL: "/static/images/reddit_icon.png"
      #   link: "https://reddit.com/submit?title=&url=https://pawprints.rit.edu/"
      # - name: "Link"
      #   imgURL: "/static/images/link_icon.png"
      #   link: "https://pawprints.rit.edu/"
